# Generated by Django 5.2.6 on 2025-09-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=150)),
                ('precio', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=150)),
            ],
        ),
    ]
